# Generated by Django 2.2 on 2019-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.URLField(blank='True'),
        ),
    ]
